package api

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/tanq16/expenseowl/internal/storage"
	"github.com/tanq16/expenseowl/internal/web"
)

// getLocalizedString retrieves a localized string from locale files
func getLocalizedString(language, key string) string {
	// Default English translations
	defaults := map[string]string{
		"common.description": "Description",
		"common.from":        "From",
		"common.to":          "To",
		"common.party":       "Party",
		"common.method":      "Method",
		"common.note":        "Note",
		"common.category":    "Category",
		"common.amount":      "Amount",
		"common.date":        "Date",
		"method.cash":        "Cash",
		"method.transfer":    "Bank Transfer",
		"method.cheque":      "Cheque",
		// Month names
		"months.january":   "January",
		"months.february":  "February",
		"months.march":     "March",
		"months.april":     "April",
		"months.may":       "May",
		"months.june":      "June",
		"months.july":      "July",
		"months.august":    "August",
		"months.september": "September",
		"months.october":   "October",
		"months.november":  "November",
		"months.december":  "December",
		// Receipt keys
		"receipt.title":          "Payment Receipt",
		"receipt.received_from":  "Received From",
		"receipt.transaction_id": "Transaction ID",
		"receipt.details":        "Transaction Details",
		"receipt.generated_on":   "Generated on",
		"receipt.generated_by":   "Generated by computer, signature not required",
		// Voucher keys
		"voucher.title":        "Payment Voucher",
		"voucher.paid_to":      "Paid To",
		"voucher.voucher_id":   "Voucher ID",
		"voucher.details":      "Expense Details",
		"voucher.for_internal": "For Internal Use Only",
		// Shared keys
		"document.amount":        "Amount",
		"table.download_receipt": "Download Receipt",
		"table.download_voucher": "Download Voucher",
		// Report keys
		"report.title":   "Transaction Report",
		"report.daily":   "Daily",
		"report.monthly": "Monthly",
		"report.yearly":  "Yearly",
	}

	// Return English default for English language
	if language == "en" || language == "" {
		if val, ok := defaults[key]; ok {
			return val
		}
		return key
	}

	// Try to load locale file for other languages
	fs := web.GetTemplates()
	localeFile := "locales/" + language + ".json"
	localeData, err := fs.ReadFile("templates/" + localeFile)
	if err != nil {
		log.Printf("Warning: Failed to load locale file %s, using English: %v\n", localeFile, err)
		if val, ok := defaults[key]; ok {
			return val
		}
		return key
	}

	// Parse locale JSON
	var locale map[string]interface{}
	if err := json.Unmarshal(localeData, &locale); err != nil {
		log.Printf("Warning: Failed to parse locale file %s: %v\n", localeFile, err)
		if val, ok := defaults[key]; ok {
			return val
		}
		return key
	}

	// Extract nested key (e.g., "common.description" -> locale["common"]["description"])
	parts := strings.Split(key, ".")
	if len(parts) != 2 {
		if val, ok := defaults[key]; ok {
			return val
		}
		return key
	}

	if section, ok := locale[parts[0]].(map[string]interface{}); ok {
		if value, ok := section[parts[1]].(string); ok {
			return value
		}
	}

	// Fallback to English
	if val, ok := defaults[key]; ok {
		return val
	}
	return key
}

// exports all expenses to CSV
func (h *Handler) ExportCSV(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeJSON(w, http.StatusMethodNotAllowed, ErrorResponse{Error: "Method not allowed"})
		return
	}
	expenses, err := h.storage.GetAllExpenses()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, ErrorResponse{Error: "Failed to retrieve expenses"})
		log.Printf("API ERROR: Failed to retrieve expenses for CSV export: %v\n", err)
		return
	}

	// Get user's language preference
	language, err := h.storage.GetLanguage()
	if err != nil {
		log.Printf("Warning: Failed to get language preference, defaulting to English: %v\n", err)
		language = "en"
	}

	w.Header().Set("Content-Type", "text/csv")
	w.Header().Set("Content-Disposition", "attachment; filename=expenses.csv")
	writer := csv.NewWriter(w)
	defer writer.Flush()

	// Write header - localized to match table view column names
	headers := []string{
		"ID",
		getLocalizedString(language, "common.description"),
		getLocalizedString(language, "common.party"),
		getLocalizedString(language, "common.method"),
		getLocalizedString(language, "common.note"),
		getLocalizedString(language, "common.category"),
		getLocalizedString(language, "common.amount"),
		getLocalizedString(language, "common.date"),
	}
	if err := writer.Write(headers); err != nil {
		log.Printf("API ERROR: Failed to write CSV header: %v\n", err)
		return
	}

	// Write records
	for _, expense := range expenses {
		method := expense.Method
		if method == "" {
			method = "cash"
		}
		// Localize method value
		localizedMethod := getLocalizedString(language, "method."+method)

		// Determine party based on transaction type
		// For gains (positive amount): party is From (where money came from)
		// For expenses (negative amount): party is To (where money went to)
		party := expense.To
		if expense.Amount > 0 {
			party = expense.From
		}

		record := []string{
			expense.ID,
			expense.Description,
			party,
			localizedMethod,
			expense.Note,
			expense.Category,
			strconv.FormatFloat(expense.Amount, 'f', 2, 64),
			expense.Date.Format(time.RFC3339),
		}
		if err := writer.Write(record); err != nil {
			log.Printf("API ERROR: Failed to write CSV record for expense ID %s: %v\n", expense.ID, err)
			continue
		}
	}
	log.Println("HTTP: Exported expenses to CSV")
}

// imports expenses from CSV
func (h *Handler) ImportCSV(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeJSON(w, http.StatusMethodNotAllowed, ErrorResponse{Error: "Method not allowed"})
		return
	}
	if err := r.ParseMultipartForm(10 << 20); err != nil { // 10MB max file size
		writeJSON(w, http.StatusBadRequest, ErrorResponse{Error: "Could not parse multipart form"})
		return
	}
	file, _, err := r.FormFile("file")
	if err != nil {
		writeJSON(w, http.StatusBadRequest, ErrorResponse{Error: "Error retrieving the file"})
		return
	}
	defer file.Close()
	reader := csv.NewReader(file)
	records, err := reader.ReadAll()
	if err != nil {
		writeJSON(w, http.StatusBadRequest, ErrorResponse{Error: "Failed to read CSV file"})
		return
	}
	if len(records) < 2 {
		writeJSON(w, http.StatusBadRequest, ErrorResponse{Error: "CSV file must have a header and at least one data row"})
		return
	}

	header := records[0]
	colMap := make(map[string]int)
	for i, col := range header {
		colMap[strings.ToLower(strings.TrimSpace(col))] = i
	}
	// Check for mandatory columns
	requiredCols := []string{"name", "category", "amount", "date"}
	for _, col := range requiredCols {
		if _, ok := colMap[col]; !ok {
			writeJSON(w, http.StatusBadRequest, ErrorResponse{Error: fmt.Sprintf("Missing required column: %s", col)})
			return
		}
	}
	// Get optional column indices
	idIdx, idExists := colMap["id"]
	tagsIdx, tagsExists := colMap["tags"]
	currencyIdx, currencyExists := colMap["currency"]

	currentCategories, err := h.storage.GetCategories()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, ErrorResponse{Error: "Could not retrieve current categories"})
		return
	}
	categorySet := make(map[string]bool)
	for _, cat := range currentCategories {
		categorySet[strings.ToLower(cat)] = true
	}
	var newCategories []string
	var importedCount, skippedCount int
	// TODO: might be worth setting default currency when we have currency updation behavior
	currencyVal, err := h.storage.GetCurrency()
	if err != nil {
		log.Printf("Error: Could not retrieve currency, shutting down import: %v\n", err)
		writeJSON(w, http.StatusInternalServerError, ErrorResponse{Error: "Could not retrieve currency"})
		return
	}

	for i, record := range records[1:] {
		if len(record) != len(header) {
			log.Printf("Warning: Skipping row %d due to incorrect column count\n", i+2)
			skippedCount++
			continue
		}

		// Check if expense exists by ID, if provided - without doing a clash resolution
		if idExists {
			id := record[idIdx]
			if _, err := h.storage.GetExpense(id); err == nil {
				log.Printf("Info: Skipping row %d because expense with ID '%s' already exists\n", i+2, id)
				skippedCount++
				continue
			}
		}

		// Check for currency field, if provided - default is retrieved
		localCurrency := currencyVal
		if currencyExists {
			currency := record[currencyIdx]
			if !slices.Contains(storage.SupportedCurrencies, currency) {
				log.Printf("Warning: Skipping row %d due to invalid currency: %s\n", i+2, currency)
				skippedCount++
				continue
			}
			localCurrency = strings.TrimSpace(currency)
		}

		amount, err := strconv.ParseFloat(record[colMap["amount"]], 64)
		if err != nil {
			log.Printf("Warning: Skipping row %d due to invalid amount: %s\n", i+2, record[colMap["amount"]])
			skippedCount++
			continue
		}
		date, err := parseDate(record[colMap["date"]])
		if err != nil {
			log.Printf("Warning: Skipping row %d due to invalid date: %v\n", i+2, err)
			skippedCount++
			continue
		}
		category := strings.TrimSpace(record[colMap["category"]])
		if _, ok := categorySet[strings.ToLower(category)]; !ok {
			newCategories = append(newCategories, category)
			categorySet[strings.ToLower(category)] = true // Add to set to handle duplicates in the same file
		}
		var tags []string
		if tagsExists {
			tagsStr := record[tagsIdx]
			if tagsStr != "" {
				tags = strings.Split(tagsStr, ",")
				for i := range tags {
					tags[i] = strings.TrimSpace(tags[i])
				}
			}
		}

		expense := storage.Expense{
			Description: strings.TrimSpace(record[colMap["name"]]),
			Category:    category,
			Amount:      amount,
			Currency:    localCurrency,
			Date:        date,
		}
		if err := expense.Validate(); err != nil {
			log.Printf("Warning: Skipping row %d due to validation error: %v\n", i+2, err)
			skippedCount++
			continue
		}
		if err := h.storage.AddExpense(expense); err != nil {
			log.Printf("Error: Could not add expense from row %d: %v\n", i+2, err)
			skippedCount++
			continue
		}
		importedCount++
		time.Sleep(10 * time.Millisecond) // Throttle to reduce storage overhead
	}

	if len(newCategories) > 0 {
		if err := h.storage.UpdateCategories(append(currentCategories, newCategories...)); err != nil {
			log.Printf("Warning: Failed to add new categories to config: %v\n", err)
		}
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"status":          "success",
		"total_processed": len(records) - 1,
		"imported":        importedCount,
		"skipped":         skippedCount,
		"new_categories":  newCategories,
	})
	log.Printf("HTTP: Imported %d expenses from CSV file. Skipped %d records.", importedCount, skippedCount)
}

// handles importing from ExpenseOwl < v4.0
// TODO: remove this in the future
func (h *Handler) ImportOldCSV(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeJSON(w, http.StatusMethodNotAllowed, ErrorResponse{Error: "Method not allowed"})
		return
	}
	if err := r.ParseMultipartForm(10 << 20); err != nil { // 10MB max file size
		writeJSON(w, http.StatusBadRequest, ErrorResponse{Error: "Could not parse multipart form"})
		return
	}
	file, _, err := r.FormFile("file")
	if err != nil {
		writeJSON(w, http.StatusBadRequest, ErrorResponse{Error: "Error retrieving the file"})
		return
	}
	defer file.Close()
	reader := csv.NewReader(file)
	records, err := reader.ReadAll()
	if err != nil {
		writeJSON(w, http.StatusBadRequest, ErrorResponse{Error: "Failed to read CSV file"})
		return
	}
	if len(records) < 2 {
		writeJSON(w, http.StatusBadRequest, ErrorResponse{Error: "CSV file must have a header and at least one data row"})
		return
	}

	header := records[0]
	colMap := make(map[string]int)
	for i, col := range header {
		colMap[strings.ToLower(strings.TrimSpace(col))] = i
	}
	requiredCols := []string{"name", "category", "amount", "date"}
	for _, col := range requiredCols {
		if _, ok := colMap[col]; !ok {
			writeJSON(w, http.StatusBadRequest, ErrorResponse{Error: fmt.Sprintf("Missing required column: %s", col)})
			return
		}
	}

	currentCategories, err := h.storage.GetCategories()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, ErrorResponse{Error: "Could not retrieve current categories"})
		return
	}
	categorySet := make(map[string]bool)
	for _, cat := range currentCategories {
		categorySet[strings.ToLower(cat)] = true
	}
	var newCategories []string
	var importedCount, skippedCount int

	for i, record := range records[1:] {
		if len(record) != len(header) {
			log.Printf("Warning: Skipping row %d due to incorrect column count\n", i+2)
			skippedCount++
			continue
		}
		amount, err := strconv.ParseFloat(record[colMap["amount"]], 64)
		if err != nil {
			log.Printf("Warning: Skipping row %d due to invalid amount: %s\n", i+2, record[colMap["amount"]])
			skippedCount++
			continue
		}
		date, err := parseDate(record[colMap["date"]])
		if err != nil {
			log.Printf("Warning: Skipping row %d due to invalid date: %v\n", i+2, err)
			skippedCount++
			continue
		}
		category := strings.TrimSpace(record[colMap["category"]])
		if _, ok := categorySet[strings.ToLower(category)]; !ok {
			newCategories = append(newCategories, category)
			categorySet[strings.ToLower(category)] = true // Add to set to handle duplicates in the same file
		}

		// switches sign for new expenseowl
		amountUpdated := amount
		if category != "Income" {
			amountUpdated = amount * -1
		}
		expense := storage.Expense{
			Description: strings.TrimSpace(record[colMap["name"]]),
			Category:    category,
			Amount:      amountUpdated,
			Date:        date,
		}
		if err := expense.Validate(); err != nil {
			log.Printf("Warning: Skipping row %d due to validation error: %v\n", i+2, err)
			skippedCount++
			continue
		}
		if err := h.storage.AddExpense(expense); err != nil {
			log.Printf("Error: Could not add expense from row %d: %v\n", i+2, err)
			skippedCount++
			continue
		}
		importedCount++
		time.Sleep(10 * time.Millisecond)
	}

	if len(newCategories) > 0 {
		if err := h.storage.UpdateCategories(append(currentCategories, newCategories...)); err != nil {
			log.Printf("Warning: Failed to add new categories to config: %v\n", err)
		}
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"status":          "success",
		"total_processed": len(records) - 1,
		"imported":        importedCount,
		"skipped":         skippedCount,
		"new_categories":  newCategories,
	})
	log.Printf("HTTP: Imported %d expenses from CSV file. Skipped %d records.", importedCount, skippedCount)
}

func parseDate(dateStr string) (time.Time, error) {
	dateFormats := []string{
		time.RFC3339,
		"2006-01-02T15:04:05Z07:00",
		"2006-01-02 15:04:05",
		"2006-01-02",
		"2006-1-2",
		"2006/01/02",
		"2006/1/2",
	}
	for _, format := range dateFormats {
		if d, err := time.Parse(format, dateStr); err == nil {
			return d.UTC(), nil
		}
	}
	return time.Time{}, fmt.Errorf("unable to parse date: %s", dateStr)
}
